# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/literate-programming-and-software-eng',
                'doc_host': 'https://Micah-vandy.github.io',
                'git_url': 'https://github.com/Micah-vandy/literate-programming-and-software-eng',
                'lib_path': 'literate_programming_and_software_eng'},
  'syms': { 'literate_programming_and_software_eng.core': { 'literate_programming_and_software_eng.core.foo': ( 'core.html#foo',
                                                                                                                'literate_programming_and_software_eng/core.py')}}}
